server:
  port: 8081
spring:
  application:
    name: swifttickets
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.5.131:3306/swifttickets?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: '072149'
  redis:
    host: 192.168.5.131
    port: 6379
    password: '072149'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.stephzhang.swifttickets.entity